# Changes here will be overwritten by Copier
_commit: v0.3.5
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage object storage
distribution_name: swh-objstorage
have_cli: true
have_workers: false
package_root: swh/objstorage
project_name: swh.objstorage
python_minimal_version: '3.11'
readme_format: rst
